-- MySQL Script generated by MySQL Workbench
-- 06/03/15 14:08:25
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `Echantillon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Echantillon` (
  `idEchantillon` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NOT NULL,
  `Marque` VARCHAR(45) NOT NULL,
  `Quantite` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idEchantillon`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Degustateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Degustateur` (
  `idDegustateur` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NOT NULL,
  `Prenom` VARCHAR(45) NOT NULL,
  `Adresse` VARCHAR(100) NOT NULL,
  `Telephone` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDegustateur`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Salle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Salle` (
  `idSalle` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Numero` VARCHAR(45) NOT NULL,
  `Batiment` VARCHAR(45) NOT NULL,
  `DateOccupation` DATETIME NOT NULL,
  `CapaciteAccueil` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idSalle`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Organisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Organisateur` (
  `idOrganisateur` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NOT NULL,
  `Prenom` VARCHAR(45) NOT NULL,
  `Adresse` VARCHAR(100) NOT NULL,
  `Telephone` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idOrganisateur`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Test`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Test` (
  `idTest` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NOT NULL,
  `DateTest` DATETIME NOT NULL,
  `Echantillon_idEchantillon` INT UNSIGNED NOT NULL,
  `Salle_idSalle` INT UNSIGNED NOT NULL,
  `Organisateur_idOrganisateur` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idTest`),
  INDEX `fk_Test_Echantillon1_idx` (`Echantillon_idEchantillon` ASC),
  INDEX `fk_Test_Salle1_idx` (`Salle_idSalle` ASC),
  INDEX `fk_Test_Preparateur1_idx` (`Organisateur_idOrganisateur` ASC),
  CONSTRAINT `fk_Test_Echantillon1`
    FOREIGN KEY (`Echantillon_idEchantillon`)
    REFERENCES `Echantillon` (`idEchantillon`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Test_Salle1`
    FOREIGN KEY (`Salle_idSalle`)
    REFERENCES `Salle` (`idSalle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Test_Preparateur1`
    FOREIGN KEY (`Organisateur_idOrganisateur`)
    REFERENCES `Organisateur` (`idOrganisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Participe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Participe` (
  `Degustateur_idDegustateur` INT UNSIGNED NOT NULL,
  `Test_idTest` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Degustateur_idDegustateur`, `Test_idTest`),
  INDEX `fk_Degustateur_has_Test_Test1_idx` (`Test_idTest` ASC),
  INDEX `fk_Degustateur_has_Test_Degustateur1_idx` (`Degustateur_idDegustateur` ASC),
  CONSTRAINT `fk_Degustateur_has_Test_Degustateur1`
    FOREIGN KEY (`Degustateur_idDegustateur`)
    REFERENCES `Degustateur` (`idDegustateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Degustateur_has_Test_Test1`
    FOREIGN KEY (`Test_idTest`)
    REFERENCES `Test` (`idTest`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Note`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Note` (
  `Echantillon_idEchantillon` INT UNSIGNED NOT NULL,
  `Degustateur_idDegustateur` INT UNSIGNED NOT NULL,
  `Aspect` INT UNSIGNED NOT NULL,
  `Gout` INT UNSIGNED NOT NULL,
  `Odeur` INT UNSIGNED NOT NULL,
  `Texture` INT UNSIGNED NOT NULL,
  `Commentaire` VARCHAR(300) NULL,
  PRIMARY KEY (`Echantillon_idEchantillon`, `Degustateur_idDegustateur`),
  INDEX `fk_Echantillon_has_Degustateur_Degustateur1_idx` (`Degustateur_idDegustateur` ASC),
  INDEX `fk_Echantillon_has_Degustateur_Echantillon1_idx` (`Echantillon_idEchantillon` ASC),
  CONSTRAINT `fk_Echantillon_has_Degustateur_Echantillon1`
    FOREIGN KEY (`Echantillon_idEchantillon`)
    REFERENCES `Echantillon` (`idEchantillon`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Echantillon_has_Degustateur_Degustateur1`
    FOREIGN KEY (`Degustateur_idDegustateur`)
    REFERENCES `Degustateur` (`idDegustateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
